import { universFont } from "@/assets/fonts/font";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${universFont.className} antialiased`}>
            <body>{children}</body>
        </html>
    );
}
