import "./globals.css";

import { Nav, WalletButtonRenderer } from "@/components";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { type PropsWithChildren } from "react";
import { Toaster } from "sonner";
import { ThirdwebProvider } from "thirdweb/react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en" className={`${GeistSans.variable} antialiased`}>
            <body>
                <Toaster position="top-center" duration={5000} closeButton richColors />
                <ThirdwebProvider>
                    <Nav>
                        <WalletButtonRenderer />
                    </Nav>
                    {children}
                </ThirdwebProvider>
            </body>
        </html>
    );
}
